# This package contains classes that understand how to serialize and deserialize specific types of information.

package(default_visibility = ["//com/jonkimbel/catfeeder:__subpackages__"])

java_library(
    name = "serializer",
    srcs = [
        "Serializer.java",
        "PreferencesSerializer.java",
    ],
    deps = [
        "//com/jonkimbel/catfeeder/backend/proto:preferences_java_proto",
    ],
)