package(default_visibility = ["//com/jonkimbel/catfeeder/backend:__subpackages__"])

java_library(
    name = "time",
    srcs = [
        "Time.java",
    ],
    deps = [
        "//com/jonkimbel/catfeeder/backend/proto:preferences_java_proto",
    ],
)