package(default_visibility = ["//com/jonkimbel/catfeeder:__subpackages__"])

java_library(
    name = "template",
    srcs = [
        "TemplateFiller.java",
    ],
    deps = [":token_finder"]
)

java_library(
    name = "token_finder",
    srcs = [
        "TokenFinder.java",
    ],
)