package(default_visibility = ["//com/jonkimbel/catfeeder:__subpackages__"])

java_proto_library(
    name = "preferences_java_proto",
    deps = [":preferences_proto"],
)

proto_library(
    name = "preferences_proto",
    srcs = ["preferences.proto"],
)