package(default_visibility = ["//com/jonkimbel/catfeeder/backend:__subpackages__"])

java_library(
    name = "api",
    srcs = [
        "PreferencesStorage.java",
    ],
    deps = [
        "//com/jonkimbel/catfeeder/backend/storage",
        "//com/jonkimbel/catfeeder/backend/proto:preferences_java_proto",
    ]
)