/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0 */

#ifndef PB_CATFEEDER_API_CAT_FEEDER_PB_H_INCLUDED
#define PB_CATFEEDER_API_CAT_FEEDER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _catfeeder_api_EmbeddedRequest {
    bool has_time_since_last_feeding_ms;
    uint64_t time_since_last_feeding_ms;
} catfeeder_api_EmbeddedRequest;

typedef struct _catfeeder_api_EmbeddedResponse {
    bool has_delay_until_next_check_in_ms;
    uint64_t delay_until_next_check_in_ms;
    bool has_delay_until_next_feeding_ms;
    uint64_t delay_until_next_feeding_ms;
} catfeeder_api_EmbeddedResponse;


/* Initializer values for message structs */
#define catfeeder_api_EmbeddedRequest_init_default {false, 0}
#define catfeeder_api_EmbeddedResponse_init_default {false, 60000ull, false, 0}
#define catfeeder_api_EmbeddedRequest_init_zero  {false, 0}
#define catfeeder_api_EmbeddedResponse_init_zero {false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define catfeeder_api_EmbeddedRequest_time_since_last_feeding_ms_tag 1
#define catfeeder_api_EmbeddedResponse_delay_until_next_check_in_ms_tag 1
#define catfeeder_api_EmbeddedResponse_delay_until_next_feeding_ms_tag 2

/* Struct field encoding specification for nanopb */
#define catfeeder_api_EmbeddedRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   time_since_last_feeding_ms,   1)
#define catfeeder_api_EmbeddedRequest_CALLBACK NULL
#define catfeeder_api_EmbeddedRequest_DEFAULT NULL

#define catfeeder_api_EmbeddedResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   delay_until_next_check_in_ms,   1) \
X(a, STATIC,   OPTIONAL, UINT64,   delay_until_next_feeding_ms,   2)
#define catfeeder_api_EmbeddedResponse_CALLBACK NULL
#define catfeeder_api_EmbeddedResponse_DEFAULT (const uint8_t*)"\x08\xe0\xd4\x03\x00"

extern const pb_msgdesc_t catfeeder_api_EmbeddedRequest_msg;
extern const pb_msgdesc_t catfeeder_api_EmbeddedResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define catfeeder_api_EmbeddedRequest_fields &catfeeder_api_EmbeddedRequest_msg
#define catfeeder_api_EmbeddedResponse_fields &catfeeder_api_EmbeddedResponse_msg

/* Maximum encoded size of messages (where known) */
#define catfeeder_api_EmbeddedRequest_size       11
#define catfeeder_api_EmbeddedResponse_size      22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
