# This package contains HTML templates for consumption by the containing package.

package(default_visibility = ["//com/jonkimbel/catfeeder/backend/template:__subpackages__"])

java_library(
    name = "data",
    resources = [
        "index.html",
        "login.html",
    ],
)