package(default_visibility = ["//com/jonkimbel/catfeeder:__subpackages__"])

java_library(
    name = "time",
    srcs = [
        "Time.java",
    ],
    deps = [
        "//com/jonkimbel/catfeeder/proto:preferences_java_proto",
    ],
)