package(default_visibility = ["//com/jonkimbel/catfeeder:__subpackages__"])

java_library(
    name = "parsers",
    srcs = [
        "PreferencesParser.java",
    ],
    deps = [
        "//com/jonkimbel/catfeeder/storage/api",
        "//com/jonkimbel/catfeeder/proto:preferences_java_proto",
    ],
)