package(default_visibility = ["//com/jonkimbel/catfeeder:__subpackages__"])

java_library(
    name = "server",
    srcs = [
        "Http.java",
        "HttpServer.java",
    ],
    deps = [
        "@maven//:org_checkerframework_checker_qual",
    ],
)