package(default_visibility = ["//com/jonkimbel/catfeeder:__subpackages__"])

java_proto_library(
    name = "cat_feeder_java_proto",
    deps = [":cat_feeder_proto"],
)

proto_library(
    name = "cat_feeder_proto",
    srcs = ["cat_feeder.proto"],
)
